// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5JzozlWc0n9RJePsHIy_0Dlyvv3sujoM',
    appId: '1:1074816415217:web:fd467a7541fe95b90d8050',
    messagingSenderId: '1074816415217',
    projectId: 'marketplace-e37b2',
    authDomain: 'marketplace-e37b2.firebaseapp.com',
    databaseURL: 'https://marketplace-e37b2-default-rtdb.firebaseio.com',
    storageBucket: 'marketplace-e37b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjGRB69thERm9lH4fOYbuENF-UB6m259Q',
    appId: '1:1074816415217:android:7f3d797252ed7b350d8050',
    messagingSenderId: '1074816415217',
    projectId: 'marketplace-e37b2',
    databaseURL: 'https://marketplace-e37b2-default-rtdb.firebaseio.com',
    storageBucket: 'marketplace-e37b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJtUm_-8S0sej_tB8MgGZhxjR6EkS7faw',
    appId: '1:1074816415217:ios:7639b2595a0cc7db0d8050',
    messagingSenderId: '1074816415217',
    projectId: 'marketplace-e37b2',
    databaseURL: 'https://marketplace-e37b2-default-rtdb.firebaseio.com',
    storageBucket: 'marketplace-e37b2.appspot.com',
    iosBundleId: 'com.example.clothing',
  );
}
